// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type TransactionSourceTypeEnum string

const (
	TransactionSourceTypeEnumFee           TransactionSourceTypeEnum = "Fee"
	TransactionSourceTypeEnumOrder         TransactionSourceTypeEnum = "Order"
	TransactionSourceTypeEnumPayment       TransactionSourceTypeEnum = "Payment"
	TransactionSourceTypeEnumServiceCharge TransactionSourceTypeEnum = "ServiceCharge"
	TransactionSourceTypeEnumUnknown       TransactionSourceTypeEnum = "Unknown"
)

func (e TransactionSourceTypeEnum) ToPointer() *TransactionSourceTypeEnum {
	return &e
}

func (e *TransactionSourceTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Fee":
		fallthrough
	case "Order":
		fallthrough
	case "Payment":
		fallthrough
	case "ServiceCharge":
		fallthrough
	case "Unknown":
		*e = TransactionSourceTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TransactionSourceTypeEnum: %v", v)
	}
}
