// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Configuration struct {
	// The company name defined in the accounting software.
	AccountingSoftwareCompanyName *string `json:"accountingSoftwareCompanyName,omitempty"`
	// Unique identifier for a company.
	CompanyID     any                    `json:"companyId,omitempty"`
	Configuration *CommerceConfiguration `json:"configuration,omitempty"`
	// True if Sync for Commerce has been configured for the company.
	Configured *bool `json:"configured,omitempty"`
	// True if Sync for Commerce is enabled for the company.
	Enable   *bool         `json:"enable,omitempty"`
	Schedule *SyncSchedule `json:"schedule,omitempty"`
}

func (o *Configuration) GetAccountingSoftwareCompanyName() *string {
	if o == nil {
		return nil
	}
	return o.AccountingSoftwareCompanyName
}

func (o *Configuration) GetCompanyID() any {
	if o == nil {
		return nil
	}
	return o.CompanyID
}

func (o *Configuration) GetConfiguration() *CommerceConfiguration {
	if o == nil {
		return nil
	}
	return o.Configuration
}

func (o *Configuration) GetConfigured() *bool {
	if o == nil {
		return nil
	}
	return o.Configured
}

func (o *Configuration) GetEnable() *bool {
	if o == nil {
		return nil
	}
	return o.Enable
}

func (o *Configuration) GetSchedule() *SyncSchedule {
	if o == nil {
		return nil
	}
	return o.Schedule
}
