// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type BilledToTypeEnum1 string

const (
	BilledToTypeEnum1Unknown       BilledToTypeEnum1 = "Unknown"
	BilledToTypeEnum1NotApplicable BilledToTypeEnum1 = "NotApplicable"
	BilledToTypeEnum1Project       BilledToTypeEnum1 = "Project"
)

func (e BilledToTypeEnum1) ToPointer() *BilledToTypeEnum1 {
	return &e
}

func (e *BilledToTypeEnum1) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "Unknown":
		fallthrough
	case "NotApplicable":
		fallthrough
	case "Project":
		*e = BilledToTypeEnum1(s)
		return nil
	default:
		return fmt.Errorf("invalid value for BilledToTypeEnum1: %s", s)
	}
}
