// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// PaymentMethodTypeEnum - Method of payment.
type PaymentMethodTypeEnum string

const (
	PaymentMethodTypeEnumUnknown      PaymentMethodTypeEnum = "Unknown"
	PaymentMethodTypeEnumCash         PaymentMethodTypeEnum = "Cash"
	PaymentMethodTypeEnumCheck        PaymentMethodTypeEnum = "Check"
	PaymentMethodTypeEnumCreditCard   PaymentMethodTypeEnum = "CreditCard"
	PaymentMethodTypeEnumDebitCard    PaymentMethodTypeEnum = "DebitCard"
	PaymentMethodTypeEnumBankTransfer PaymentMethodTypeEnum = "BankTransfer"
	PaymentMethodTypeEnumOther        PaymentMethodTypeEnum = "Other"
)

func (e PaymentMethodTypeEnum) ToPointer() *PaymentMethodTypeEnum {
	return &e
}

func (e *PaymentMethodTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "Cash":
		fallthrough
	case "Check":
		fallthrough
	case "CreditCard":
		fallthrough
	case "DebitCard":
		fallthrough
	case "BankTransfer":
		fallthrough
	case "Other":
		*e = PaymentMethodTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentMethodTypeEnum: %v", v)
	}
}
