// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// StatusEnum - Current state of the tracking category.
type StatusEnum string

const (
	StatusEnumUnknown  StatusEnum = "Unknown"
	StatusEnumActive   StatusEnum = "Active"
	StatusEnumArchived StatusEnum = "Archived"
)

func (e StatusEnum) ToPointer() *StatusEnum {
	return &e
}

func (e *StatusEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "Active":
		fallthrough
	case "Archived":
		*e = StatusEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StatusEnum: %v", v)
	}
}
