// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// IntegrationType - Type of transaction that has been processed e.g. Expense or Bank Feed.
type IntegrationType string

const (
	IntegrationTypeExpenses  IntegrationType = "expenses"
	IntegrationTypeBankfeeds IntegrationType = "bankfeeds"
)

func (e IntegrationType) ToPointer() *IntegrationType {
	return &e
}
func (e *IntegrationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "expenses":
		fallthrough
	case "bankfeeds":
		*e = IntegrationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationType: %v", v)
	}
}
