// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type UpdateExpenseResponse struct {
	// Unique identifier for the update expense sync.
	SyncID *string `json:"syncId,omitempty"`
}

func (o *UpdateExpenseResponse) GetSyncID() *string {
	if o == nil {
		return nil
	}
	return o.SyncID
}
