// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// SupplierStatus - Status of the supplier.
type SupplierStatus string

const (
	SupplierStatusUnknown  SupplierStatus = "Unknown"
	SupplierStatusActive   SupplierStatus = "Active"
	SupplierStatusArchived SupplierStatus = "Archived"
)

func (e SupplierStatus) ToPointer() *SupplierStatus {
	return &e
}
func (e *SupplierStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "Active":
		fallthrough
	case "Archived":
		*e = SupplierStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SupplierStatus: %v", v)
	}
}
