workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    accounting-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Accounting.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/accounting-source
    assess-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Assess.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/assess-source
    bank-feeds-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Bank-Feeds.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/bank-feeds-source
    banking-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Banking.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/banking-source
    commerce-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Commerce.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/commerce-source
    common-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Platform.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/common-source
    files-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Files.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/files-source
    lending-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Lending.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/lending-source
    platform-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Platform.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/platform-source
    sync-for-commerce-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Commerce.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/sync-for-commerce-source
    sync-for-commerce-version-1-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Commerce-v1.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/sync-for-commerce-version-1-source
    sync-for-expenses-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Expenses.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/sync-for-expenses-source
    sync-for-expenses-version-1-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Expenses-v1.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/sync-for-expenses-version-1-source
    sync-for-payables-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Payables.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/sync-for-payables-source
    sync-for-payables-version-1-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Payables-v1.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/sync-for-payables-version-1-source
    sync-for-payroll-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Payroll.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/sync-for-payroll-source
targets:
    accounting-library:
        target: go
        source: accounting-source
        output: previous-versions/accounting
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/accounting-source-go-code-samples
            blocking: false
    assess-library:
        target: go
        source: assess-source
        output: previous-versions/assess
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/assess-source-go-code-samples
            blocking: false
    bank-feeds-library:
        target: go
        source: bank-feeds-source
        output: bank-feeds
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/bank-feeds-source-go-code-samples
            blocking: false
    banking-library:
        target: go
        source: banking-source
        output: previous-versions/banking
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/banking-source-go-code-samples
            blocking: false
    commerce-library:
        target: go
        source: commerce-source
        output: previous-versions/commerce
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/commerce-source-go-code-samples
            blocking: false
    common-library:
        target: go
        source: common-source
        output: previous-versions/common
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/common-source-go-code-samples
            blocking: false
    files-library:
        target: go
        source: files-source
        output: previous-versions/files
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/files-source-go-code-samples
            blocking: false
    lending-library:
        target: go
        source: lending-source
        output: lending
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/lending-source-go-code-samples
            blocking: false
    platform-library:
        target: go
        source: platform-source
        output: platform
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/platform-source-go-code-samples
            blocking: false
    sync-for-commerce-library:
        target: go
        source: sync-for-commerce-source
        output: sync-for-commerce
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/sync-for-commerce-source-go-code-samples
            blocking: false
    sync-for-commerce-version-1-library:
        target: go
        source: sync-for-commerce-version-1-source
        output: previous-versions/sync-for-commerce-version-1
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/sync-for-commerce-version-1-source-go-code-samples
            blocking: false
    sync-for-expenses-library:
        target: go
        source: sync-for-expenses-source
        output: sync-for-expenses
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/sync-for-expenses-source-go-code-samples
            blocking: false
    sync-for-expenses-version-1-library:
        target: go
        source: sync-for-expenses-version-1-source
        output: previous-versions/sync-for-expenses-version-1
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/sync-for-expenses-version-1-source-go-code-samples
            blocking: false
    sync-for-payables-library:
        target: go
        source: sync-for-payables-source
        output: sync-for-payables
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/sync-for-payables-source-go-code-samples
            blocking: false
    sync-for-payables-version-1-library:
        target: go
        source: sync-for-payables-version-1-source
        output: previous-versions/sync-for-payables-version-1
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/sync-for-payables-version-1-source-go-code-samples
            blocking: false
    sync-for-payroll-library:
        target: go
        source: sync-for-payroll-source
        output: sync-for-payroll
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/sync-for-payroll-source-go-code-samples
            blocking: false
