// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// TaxRateRef - Reference to the tax rate to which the line item is linked.
type TaxRateRef struct {
	// Applicable tax rate.
	EffectiveTaxRate *float64 `json:"effectiveTaxRate,omitempty"`
	// Unique identifier for the tax rate in the accounting platform.
	ID *string `json:"id,omitempty"`
	// Name of the tax rate in the accounting platform.
	Name *string `json:"name,omitempty"`
}

func (o *TaxRateRef) GetEffectiveTaxRate() *float64 {
	if o == nil {
		return nil
	}
	return o.EffectiveTaxRate
}

func (o *TaxRateRef) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TaxRateRef) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
