// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Result struct {
	// The error description for the attempted creation of the source account.
	Error *string `json:"error,omitempty"`
	// The error status code for the attempted creation of the source account.
	StatusCode *string `json:"statusCode,omitempty"`
}

func (o *Result) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *Result) GetStatusCode() *string {
	if o == nil {
		return nil
	}
	return o.StatusCode
}

// SourceAccountBatchErrorResponse - Describes the error that occured when trying to create the specified source account.
type SourceAccountBatchErrorResponse struct {
	Result *Result `json:"result,omitempty"`
	// Unique ID for the source account.
	SourceAccountID *string `json:"sourceAccountId,omitempty"`
}

func (o *SourceAccountBatchErrorResponse) GetResult() *Result {
	if o == nil {
		return nil
	}
	return o.Result
}

func (o *SourceAccountBatchErrorResponse) GetSourceAccountID() *string {
	if o == nil {
		return nil
	}
	return o.SourceAccountID
}
