// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/codatio/client-sdk-go/common/pkg/models/shared"
	"net/http"
)

type GetCreateUpdateModelOptionsByDataTypeRequest struct {
	CompanyID    string `pathParam:"style=simple,explode=false,name=companyId"`
	ConnectionID string `pathParam:"style=simple,explode=false,name=connectionId"`
	// The key of a Codat data type
	DataType shared.DataTypeEnum `pathParam:"style=simple,explode=false,name=dataType"`
}

type GetCreateUpdateModelOptionsByDataTypeResponse struct {
	ContentType string
	// OK
	PushOption  *shared.PushOption
	StatusCode  int
	RawResponse *http.Response
}
