// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AccountingBankAccounts struct {
	Links Links `json:"_links"`
	// Current page number.
	PageNumber int64 `json:"pageNumber"`
	// Number of items to return in results array.
	PageSize int64                   `json:"pageSize"`
	Results  []AccountingBankAccount `json:"results,omitempty"`
	// Total number of items.
	TotalResults int64 `json:"totalResults"`
}

func (o *AccountingBankAccounts) GetLinks() Links {
	if o == nil {
		return Links{}
	}
	return o.Links
}

func (o *AccountingBankAccounts) GetPageNumber() int64 {
	if o == nil {
		return 0
	}
	return o.PageNumber
}

func (o *AccountingBankAccounts) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *AccountingBankAccounts) GetResults() []AccountingBankAccount {
	if o == nil {
		return nil
	}
	return o.Results
}

func (o *AccountingBankAccounts) GetTotalResults() int64 {
	if o == nil {
		return 0
	}
	return o.TotalResults
}
