// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// EnhancedCashFlowTransactions - > **Categorization engine**
// >
// > The categorization engine uses machine learning and has been fully trained against Plaid and TrueLayer banking data sources. It is not fully trained against the Basiq banking data source.
//
// The Enhanced Cash Flow Transactions endpoint provides a fully categorized list of banking transactions for a company. Accounts and transaction data are obtained from the company's banking data sources.
type EnhancedCashFlowTransactions struct {
	DataSources []DataSource `json:"dataSources,omitempty"`
	// Report additional information, which is specific to Lending API reports.
	ReportInfo  *ReportInfo            `json:"reportInfo,omitempty"`
	ReportItems []EnhancedCashFlowItem `json:"reportItems,omitempty"`
}

func (o *EnhancedCashFlowTransactions) GetDataSources() []DataSource {
	if o == nil {
		return nil
	}
	return o.DataSources
}

func (o *EnhancedCashFlowTransactions) GetReportInfo() *ReportInfo {
	if o == nil {
		return nil
	}
	return o.ReportInfo
}

func (o *EnhancedCashFlowTransactions) GetReportItems() []EnhancedCashFlowItem {
	if o == nil {
		return nil
	}
	return o.ReportItems
}
