// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ReportGenerationPayload struct {
	// Unique identifier of the report.
	ID               *string           `json:"id,omitempty"`
	ReferenceCompany *CompanyReference `json:"referenceCompany,omitempty"`
}

func (o *ReportGenerationPayload) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ReportGenerationPayload) GetReferenceCompany() *CompanyReference {
	if o == nil {
		return nil
	}
	return o.ReferenceCompany
}
