// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// BankTransactionTypeEnum - Type of transaction for the bank statement line
type BankTransactionTypeEnum string

const (
	BankTransactionTypeEnumUnknown     BankTransactionTypeEnum = "Unknown"
	BankTransactionTypeEnumCredit      BankTransactionTypeEnum = "Credit"
	BankTransactionTypeEnumDebit       BankTransactionTypeEnum = "Debit"
	BankTransactionTypeEnumInt         BankTransactionTypeEnum = "Int"
	BankTransactionTypeEnumDiv         BankTransactionTypeEnum = "Div"
	BankTransactionTypeEnumFee         BankTransactionTypeEnum = "Fee"
	BankTransactionTypeEnumSerChg      BankTransactionTypeEnum = "SerChg"
	BankTransactionTypeEnumDep         BankTransactionTypeEnum = "Dep"
	BankTransactionTypeEnumAtm         BankTransactionTypeEnum = "Atm"
	BankTransactionTypeEnumPos         BankTransactionTypeEnum = "Pos"
	BankTransactionTypeEnumXfer        BankTransactionTypeEnum = "Xfer"
	BankTransactionTypeEnumCheck       BankTransactionTypeEnum = "Check"
	BankTransactionTypeEnumPayment     BankTransactionTypeEnum = "Payment"
	BankTransactionTypeEnumCash        BankTransactionTypeEnum = "Cash"
	BankTransactionTypeEnumDirectDep   BankTransactionTypeEnum = "DirectDep"
	BankTransactionTypeEnumDirectDebit BankTransactionTypeEnum = "DirectDebit"
	BankTransactionTypeEnumRepeatPmt   BankTransactionTypeEnum = "RepeatPmt"
	BankTransactionTypeEnumOther       BankTransactionTypeEnum = "Other"
)

func (e BankTransactionTypeEnum) ToPointer() *BankTransactionTypeEnum {
	return &e
}

func (e *BankTransactionTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "Unknown":
		fallthrough
	case "Credit":
		fallthrough
	case "Debit":
		fallthrough
	case "Int":
		fallthrough
	case "Div":
		fallthrough
	case "Fee":
		fallthrough
	case "SerChg":
		fallthrough
	case "Dep":
		fallthrough
	case "Atm":
		fallthrough
	case "Pos":
		fallthrough
	case "Xfer":
		fallthrough
	case "Check":
		fallthrough
	case "Payment":
		fallthrough
	case "Cash":
		fallthrough
	case "DirectDep":
		fallthrough
	case "DirectDebit":
		fallthrough
	case "RepeatPmt":
		fallthrough
	case "Other":
		*e = BankTransactionTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for BankTransactionTypeEnum: %s", s)
	}
}
