// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/codatio/client-sdk-go/lending/pkg/models/shared"
	"net/http"
)

type GetBankingTransactionRequest struct {
	CompanyID    string `pathParam:"style=simple,explode=false,name=companyId"`
	ConnectionID string `pathParam:"style=simple,explode=false,name=connectionId"`
	// The unique identifier for a transaction
	TransactionID string `pathParam:"style=simple,explode=false,name=transactionId"`
}

func (o *GetBankingTransactionRequest) GetCompanyID() string {
	if o == nil {
		return ""
	}
	return o.CompanyID
}

func (o *GetBankingTransactionRequest) GetConnectionID() string {
	if o == nil {
		return ""
	}
	return o.ConnectionID
}

func (o *GetBankingTransactionRequest) GetTransactionID() string {
	if o == nil {
		return ""
	}
	return o.TransactionID
}

type GetBankingTransactionResponse struct {
	// Success
	BankingTransaction *shared.BankingTransaction
	ContentType        string
	StatusCode         int
	RawResponse        *http.Response
}

func (o *GetBankingTransactionResponse) GetBankingTransaction() *shared.BankingTransaction {
	if o == nil {
		return nil
	}
	return o.BankingTransaction
}

func (o *GetBankingTransactionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetBankingTransactionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetBankingTransactionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
