// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/codatio/client-sdk-go/synccommerce/pkg/models/shared"
	"net/http"
)

type CreateConnectionRequest struct {
	RequestBody *string `request:"mediaType=application/json"`
	CompanyID   string  `pathParam:"style=simple,explode=false,name=companyId"`
}

type CreateConnectionResponse struct {
	// Success
	Connection  *shared.Connection
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
