// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/codatio/client-sdk-go/accounting/pkg/models/shared"
	"net/http"
)

type GetAllBankAccountRequest struct {
	// Unique identifier for an account
	AccountID string `pathParam:"style=simple,explode=false,name=accountId"`
	CompanyID string `pathParam:"style=simple,explode=false,name=companyId"`
	// Codat query string. [Read more](https://docs.codat.io/using-the-api/querying).
	Query *string `queryParam:"style=form,explode=true,name=query"`
}

type GetAllBankAccountResponse struct {
	// Success
	BankStatementAccount *shared.BankStatementAccount
	ContentType          string
	StatusCode           int
	RawResponse          *http.Response
}
