// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/codatio/client-sdk-go/accounting/pkg/models/shared"
	"net/http"
)

type GetPurchaseOrderRequest struct {
	CompanyID       string `pathParam:"style=simple,explode=false,name=companyId"`
	PurchaseOrderID string `pathParam:"style=simple,explode=false,name=purchaseOrderId"`
}

func (o *GetPurchaseOrderRequest) GetCompanyID() string {
	if o == nil {
		return ""
	}
	return o.CompanyID
}

func (o *GetPurchaseOrderRequest) GetPurchaseOrderID() string {
	if o == nil {
		return ""
	}
	return o.PurchaseOrderID
}

// GetPurchaseOrder409ApplicationJSON - The data type's dataset has not been requested or is still syncing.
type GetPurchaseOrder409ApplicationJSON struct {
	CanBeRetried      *string `json:"canBeRetried,omitempty"`
	CorrelationID     *string `json:"correlationId,omitempty"`
	DetailedErrorCode *int64  `json:"detailedErrorCode,omitempty"`
	Error             *string `json:"error,omitempty"`
	Service           *string `json:"service,omitempty"`
	StatusCode        *int64  `json:"statusCode,omitempty"`
}

func (o *GetPurchaseOrder409ApplicationJSON) GetCanBeRetried() *string {
	if o == nil {
		return nil
	}
	return o.CanBeRetried
}

func (o *GetPurchaseOrder409ApplicationJSON) GetCorrelationID() *string {
	if o == nil {
		return nil
	}
	return o.CorrelationID
}

func (o *GetPurchaseOrder409ApplicationJSON) GetDetailedErrorCode() *int64 {
	if o == nil {
		return nil
	}
	return o.DetailedErrorCode
}

func (o *GetPurchaseOrder409ApplicationJSON) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *GetPurchaseOrder409ApplicationJSON) GetService() *string {
	if o == nil {
		return nil
	}
	return o.Service
}

func (o *GetPurchaseOrder409ApplicationJSON) GetStatusCode() *int64 {
	if o == nil {
		return nil
	}
	return o.StatusCode
}

type GetPurchaseOrderResponse struct {
	ContentType string
	// Success
	PurchaseOrder *shared.PurchaseOrder
	StatusCode    int
	RawResponse   *http.Response
	// The data type's dataset has not been requested or is still syncing.
	GetPurchaseOrder409ApplicationJSONObject *GetPurchaseOrder409ApplicationJSON
	// Your API request was not properly authorized.
	Schema *shared.Schema
}

func (o *GetPurchaseOrderResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetPurchaseOrderResponse) GetPurchaseOrder() *shared.PurchaseOrder {
	if o == nil {
		return nil
	}
	return o.PurchaseOrder
}

func (o *GetPurchaseOrderResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetPurchaseOrderResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetPurchaseOrderResponse) GetGetPurchaseOrder409ApplicationJSONObject() *GetPurchaseOrder409ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetPurchaseOrder409ApplicationJSONObject
}

func (o *GetPurchaseOrderResponse) GetSchema() *shared.Schema {
	if o == nil {
		return nil
	}
	return o.Schema
}
