name: Generate Platform library
'on':
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
  workflow_call:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
      secrets:
        github_access_token:
          description: Github Access Token
          required: true
        speakeasy_api_key:
          description: Speakeasy API Key
          required: true
        slack_webhook_url:
          description: Slack Webhook URL
          required: true
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v14
    with:
      speakeasy_version: latest
      openapi_doc_location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Platform.yaml
      languages: |-
        - go: ./platform
      create_release: true
      mode: pr
      force: ${{ github.event.inputs.force }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
