name: Release Sync for Commerce version 1 library
'on':
  push:
    paths:
    - previous-versions/sync-for-commerce-version-1/RELEASES.md
    branches:
    - main
jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v15
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
